CREATE TABLE dbs_mtwSignOf (
id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
datum DATETIME NOT NULL,
kunde VARCHAR(255) NOT NULL,
unterschrift LONGTEXT NOT NULL,
stunden FLOAT NOT NULL,
von VARCHAR(255) NOT NULL,
bis VARCHAR(255) NOT NULL
) ENGINE= InnoDb;

DROP TABLE dbs_mtwSignOf